import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :learn_elixir_landing, LearnElixirLandingWeb.Endpoint,
  server: true,
  url: [host: "learn-elixir.dev", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

config :learn_elixir_landing, :tracking_tags_enabled?, true

config :learn_elixir_landing, LearnElixirLanding.Mailer,
  adapter: Swoosh.Adapters.AmazonSES


import_config "prod.secret.exs"
